name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask tests (if any)
      run: |
        echo "No tests yet — this is a placeholder."
        # You can add `pytest` or similar later.

    # 🛠️ Deployment step placeholder (we’ll configure it in the next phase)
    - name: Deploy to EC2 (Coming soon!)
      run: echo "Deployment step goes here..."

